In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("messy_sales_data-1.csv")

In [3]:
df

,OrderID,OrderDate,Product,Quantity,UnitPrice,Region,Channel,Customer
0,1000,2026-01-01,LAPTOP,2.0,"$500,00",West,NaN,david
1,1001,2026-01-02,Laptop,NaN,"$500,00",NaN,STORE,BOB
2,1002,NaN,monitor,5.0,$1000,east,In Store,Charlie
3,1003,2026-01-04,Laptop,3.0,2500,south,NaN,Alice
4,1004,NaN,laptop,NaN,"$1500,00",West,In Store,Charlie
5,1005,2026-01-06,mouse,3.0,$2000,North,online,BOB
6,1006,Jan 7 2026,KEYBOARD,NaN,$1000,south,STORE,Charlie
7,1007,01/8/2026,keyboard,1.0,"$1000,00",south,online,Alice
8,1008,01/9/2026,MONITOR,-1.0,"2000,00",south,In Store,Charlie
9,1009,01/10/2026,PHONE,-1.0,2500,North,In Store,BOB
10,1010,NaN,laptop,2.0,$1000,West,STORE,david
11,1011,NaN,Monitor,1.0,$500,North,online,Alice
12,1012,Jan 13 2026,Headphones,-1.0,"$1500,00",NaN,Online,Charlie
13,1013,01/2/2026,phone,5.0,$2500,south,Online,Alice
14,1014,Jan 15 2026,MOUSE,2.0,$2500,south,Online,NaN
15,1015,01/4/2026,phone,2.0,$1500,east,NaN,BOB
16,1016,Jan 17 2026,HEADPHONES,4.0,2500,West,online,Alice
17,1017,01/6/2026,Monitor,-1.0,"500,00",North,Online,NaN
18,1018,01/7/2026,Tablet,2.0,$2500,south,STORE,BOB
19,1019,2026-01-02,Laptop,4.0,$2000,West,Online,david
20,1020,Jan 21 2026,MOUSE,2.0,2500,North,STORE,BOB
21,1021,2026-01-04,headphones,1.0,$500,West,Online,BOB
22,1022,01/11/2026,Headphones,4.0,500,south,online,david
23,1023,Jan 24 2026,Headphones,5.0,$2500,east,online,BOB
24,1024,2026-01-07,MONITOR,3.0,500,NaN,In Store,Alice
25,1025,2026-01-08,mouse,-1.0,"1000,00",NaN,In Store,NaN
26,1026,2026-01-09,Monitor,NaN,2500,North,In Store,Charlie
27,1027,NaN,phone,3.0,500,NaN,Online,Alice
28,1028,01/5/2026,monitor,1.0,1000,NaN,online,NaN
29,1029,2026-01-03,KEYBOARD,-1.0,$500,West,Online,NaN
30,1030,01/7/2026,Tablet,3.0,"$1000,00",NaN,STORE,Charlie
31,1031,2026-01-05,laptop,1.0,500,North,In Store,david
32,1032,NaN,Monitor,-1.0,"$1000,00",NaN,NaN,BOB
33,1033,NaN,phone,5.0,$500,east,Online,Charlie
34,1034,NaN,monitor,2.0,"$1000,00",south,Online,BOB
35,1035,Jan 8 2026,mouse,5.0,"1000,00",West,STORE,Alice
36,1036,NaN,phone,3.0,"$1500,00",east,Online,BOB
37,1037,NaN,Tablet,5.0,1500,NaN,online,Alice
38,1038,2026-01-03,tablet,3.0,500,North,STORE,NaN
39,1039,2026-01-04,HEADPHONES,1.0,"2000,00",NaN,In Store,Charlie

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    40 non-null     int64
 1   OrderDate  30 non-null     object
 2   Product    40 non-null     object
 3   Quantity   36 non-null     float64
 4   UnitPrice  40 non-null     object
 5   Region     30 non-null     object
 6   Channel    36 non-null     object
 7   Customer   34 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.6+ KB

In [5]:
df.describe()

           OrderID   Quantity
count    40.000000  36.000000
mean   1019.500000   2.111111
std      11.690452   2.011080
min    1000.000000  -1.000000
25%    1009.750000   1.000000
50%    1019.500000   2.000000
75%    1029.250000   3.250000
max    1039.000000   5.000000

In [6]:
df.dtypes

OrderID        int64
OrderDate     object
Product       object
Quantity     float64
UnitPrice     object
Region        object
Channel       object
Customer      object
dtype: object

In [11]:
df.columns = df.columns.str.lower().str.strip()
dd = df
dd

,orderid,orderdate,product,quantity,unitprice,region,channel,customer
0,1000,2026-01-01,LAPTOP,2.0,"$500,00",West,NaN,david
1,1001,2026-01-02,Laptop,NaN,"$500,00",NaN,STORE,BOB
2,1002,NaT,monitor,5.0,$1000,east,In Store,Charlie
3,1003,2026-01-04,Laptop,3.0,2500,south,NaN,Alice
4,1004,NaT,laptop,NaN,"$1500,00",West,In Store,Charlie
5,1005,2026-01-06,mouse,3.0,$2000,North,online,BOB
6,1006,2026-01-07,KEYBOARD,NaN,$1000,south,STORE,Charlie
7,1007,2026-01-08,keyboard,1.0,"$1000,00",south,online,Alice
8,1008,2026-01-09,MONITOR,-1.0,"2000,00",south,In Store,Charlie
9,1009,2026-01-10,PHONE,-1.0,2500,North,In Store,BOB
10,1010,NaT,laptop,2.0,$1000,West,STORE,david
11,1011,NaT,Monitor,1.0,$500,North,online,Alice
12,1012,2026-01-13,Headphones,-1.0,"$1500,00",NaN,Online,Charlie
13,1013,2026-01-02,phone,5.0,$2500,south,Online,Alice
14,1014,2026-01-15,MOUSE,2.0,$2500,south,Online,NaN
15,1015,2026-01-04,phone,2.0,$1500,east,NaN,BOB
16,1016,2026-01-17,HEADPHONES,4.0,2500,West,online,Alice
17,1017,2026-01-06,Monitor,-1.0,"500,00",North,Online,NaN
18,1018,2026-01-07,Tablet,2.0,$2500,south,STORE,BOB
19,1019,2026-01-02,Laptop,4.0,$2000,West,Online,david
20,1020,2026-01-21,MOUSE,2.0,2500,North,STORE,BOB
21,1021,2026-01-04,headphones,1.0,$500,West,Online,BOB
22,1022,2026-01-11,Headphones,4.0,500,south,online,david
23,1023,2026-01-24,Headphones,5.0,$2500,east,online,BOB
24,1024,2026-01-07,MONITOR,3.0,500,NaN,In Store,Alice
25,1025,2026-01-08,mouse,-1.0,"1000,00",NaN,In Store,NaN
26,1026,2026-01-09,Monitor,NaN,2500,North,In Store,Charlie
27,1027,NaT,phone,3.0,500,NaN,Online,Alice
28,1028,2026-01-05,monitor,1.0,1000,NaN,online,NaN
29,1029,2026-01-03,KEYBOARD,-1.0,$500,West,Online,NaN
30,1030,2026-01-07,Tablet,3.0,"$1000,00",NaN,STORE,Charlie
31,1031,2026-01-05,laptop,1.0,500,North,In Store,david
32,1032,NaT,Monitor,-1.0,"$1000,00",NaN,NaN,BOB
33,1033,NaT,phone,5.0,$500,east,Online,Charlie
34,1034,NaT,monitor,2.0,"$1000,00",south,Online,BOB
35,1035,2026-01-08,mouse,5.0,"1000,00",West,STORE,Alice
36,1036,NaT,phone,3.0,"$1500,00",east,Online,BOB
37,1037,NaT,Tablet,5.0,1500,NaN,online,Alice
38,1038,2026-01-03,tablet,3.0,500,North,STORE,NaN
39,1039,2026-01-04,HEADPHONES,1.0,"2000,00",NaN,In Store,Charlie

In [12]:
dd["orderdate"] = pd.to_datetime(dd["orderdate"],format ="mixed")

In [13]:
dd["orderdate"]

0    2026-01-01
1    2026-01-02
2           NaT
3    2026-01-04
4           NaT
5    2026-01-06
6    2026-01-07
7    2026-01-08
8    2026-01-09
9    2026-01-10
10          NaT
11          NaT
12   2026-01-13
13   2026-01-02
14   2026-01-15
15   2026-01-04
16   2026-01-17
17   2026-01-06
18   2026-01-07
19   2026-01-02
20   2026-01-21
21   2026-01-04
22   2026-01-11
23   2026-01-24
24   2026-01-07
25   2026-01-08
26   2026-01-09
27          NaT
28   2026-01-05
29   2026-01-03
30   2026-01-07
31   2026-01-05
32          NaT
33          NaT
34          NaT
35   2026-01-08
36          NaT
37          NaT
38   2026-01-03
39   2026-01-04
Name: orderdate, dtype: datetime64[ns]

In [14]:
dd["unitprice"] = (
    dd["unitprice"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", ".", regex=False)
)

dd["unitprice"] = pd.to_numeric(dd["unitprice"], errors="coerce")

In [15]:
dd["unitprice"]

0      500.0
1      500.0
2     1000.0
3     2500.0
4     1500.0
5     2000.0
6     1000.0
7     1000.0
8     2000.0
9     2500.0
10    1000.0
11     500.0
12    1500.0
13    2500.0
14    2500.0
15    1500.0
16    2500.0
17     500.0
18    2500.0
19    2000.0
20    2500.0
21     500.0
22     500.0
23    2500.0
24     500.0
25    1000.0
26    2500.0
27     500.0
28    1000.0
29     500.0
30    1000.0
31     500.0
32    1000.0
33     500.0
34    1000.0
35    1000.0
36    1500.0
37    1500.0
38     500.0
39    2000.0
Name: unitprice, dtype: float64

In [16]:
dd["region"] = dd["region"].fillna("unknown")

In [17]:
dd["channel"] = dd["channel"].fillna("unknown")

In [18]:
dd["customer"] = dd["customer"].fillna("unknown")

In [19]:
dd["quantity"] = dd["quantity"].fillna(
    dd.groupby("product")["quantity"].transform("median")
)

In [20]:
cols = ["product","region","channel","customer"]

In [21]:
for col in cols:
    dd[col] = dd[col].str.strip().str.title()

In [22]:
dd

,orderid,orderdate,product,quantity,unitprice,region,channel,customer
0,1000,2026-01-01,Laptop,2.0,500.0,West,Unknown,David
1,1001,2026-01-02,Laptop,3.5,500.0,Unknown,Store,Bob
2,1002,NaT,Monitor,5.0,1000.0,East,In Store,Charlie
3,1003,2026-01-04,Laptop,3.0,2500.0,South,Unknown,Alice
4,1004,NaT,Laptop,1.5,1500.0,West,In Store,Charlie
5,1005,2026-01-06,Mouse,3.0,2000.0,North,Online,Bob
6,1006,2026-01-07,Keyboard,-1.0,1000.0,South,Store,Charlie
7,1007,2026-01-08,Keyboard,1.0,1000.0,South,Online,Alice
8,1008,2026-01-09,Monitor,-1.0,2000.0,South,In Store,Charlie
9,1009,2026-01-10,Phone,-1.0,2500.0,North,In Store,Bob
10,1010,NaT,Laptop,2.0,1000.0,West,Store,David
11,1011,NaT,Monitor,1.0,500.0,North,Online,Alice
12,1012,2026-01-13,Headphones,-1.0,1500.0,Unknown,Online,Charlie
13,1013,2026-01-02,Phone,5.0,2500.0,South,Online,Alice
14,1014,2026-01-15,Mouse,2.0,2500.0,South,Online,Unknown
15,1015,2026-01-04,Phone,2.0,1500.0,East,Unknown,Bob
16,1016,2026-01-17,Headphones,4.0,2500.0,West,Online,Alice
17,1017,2026-01-06,Monitor,-1.0,500.0,North,Online,Unknown
18,1018,2026-01-07,Tablet,2.0,2500.0,South,Store,Bob
19,1019,2026-01-02,Laptop,4.0,2000.0,West,Online,David
20,1020,2026-01-21,Mouse,2.0,2500.0,North,Store,Bob
21,1021,2026-01-04,Headphones,1.0,500.0,West,Online,Bob
22,1022,2026-01-11,Headphones,4.0,500.0,South,Online,David
23,1023,2026-01-24,Headphones,5.0,2500.0,East,Online,Bob
24,1024,2026-01-07,Monitor,3.0,500.0,Unknown,In Store,Alice
25,1025,2026-01-08,Mouse,-1.0,1000.0,Unknown,In Store,Unknown
26,1026,2026-01-09,Monitor,-1.0,2500.0,North,In Store,Charlie
27,1027,NaT,Phone,3.0,500.0,Unknown,Online,Alice
28,1028,2026-01-05,Monitor,1.0,1000.0,Unknown,Online,Unknown
29,1029,2026-01-03,Keyboard,-1.0,500.0,West,Online,Unknown
30,1030,2026-01-07,Tablet,3.0,1000.0,Unknown,Store,Charlie
31,1031,2026-01-05,Laptop,1.0,500.0,North,In Store,David
32,1032,NaT,Monitor,-1.0,1000.0,Unknown,Unknown,Bob
33,1033,NaT,Phone,5.0,500.0,East,Online,Charlie
34,1034,NaT,Monitor,2.0,1000.0,South,Online,Bob
35,1035,2026-01-08,Mouse,5.0,1000.0,West,Store,Alice
36,1036,NaT,Phone,3.0,1500.0,East,Online,Bob
37,1037,NaT,Tablet,5.0,1500.0,Unknown,Online,Alice
38,1038,2026-01-03,Tablet,3.0,500.0,North,Store,Unknown
39,1039,2026-01-04,Headphones,1.0,2000.0,Unknown,In Store,Charlie

In [23]:
dd.loc[df["quantity"]<0,"quantity"]=dd.loc[df["quantity"]<0,"quantity"].abs()

In [24]:
dd

,orderid,orderdate,product,quantity,unitprice,region,channel,customer
0,1000,2026-01-01,Laptop,2.0,500.0,West,Unknown,David
1,1001,2026-01-02,Laptop,3.5,500.0,Unknown,Store,Bob
2,1002,NaT,Monitor,5.0,1000.0,East,In Store,Charlie
3,1003,2026-01-04,Laptop,3.0,2500.0,South,Unknown,Alice
4,1004,NaT,Laptop,1.5,1500.0,West,In Store,Charlie
5,1005,2026-01-06,Mouse,3.0,2000.0,North,Online,Bob
6,1006,2026-01-07,Keyboard,1.0,1000.0,South,Store,Charlie
7,1007,2026-01-08,Keyboard,1.0,1000.0,South,Online,Alice
8,1008,2026-01-09,Monitor,1.0,2000.0,South,In Store,Charlie
9,1009,2026-01-10,Phone,1.0,2500.0,North,In Store,Bob
10,1010,NaT,Laptop,2.0,1000.0,West,Store,David
11,1011,NaT,Monitor,1.0,500.0,North,Online,Alice
12,1012,2026-01-13,Headphones,1.0,1500.0,Unknown,Online,Charlie
13,1013,2026-01-02,Phone,5.0,2500.0,South,Online,Alice
14,1014,2026-01-15,Mouse,2.0,2500.0,South,Online,Unknown
15,1015,2026-01-04,Phone,2.0,1500.0,East,Unknown,Bob
16,1016,2026-01-17,Headphones,4.0,2500.0,West,Online,Alice
17,1017,2026-01-06,Monitor,1.0,500.0,North,Online,Unknown
18,1018,2026-01-07,Tablet,2.0,2500.0,South,Store,Bob
19,1019,2026-01-02,Laptop,4.0,2000.0,West,Online,David
20,1020,2026-01-21,Mouse,2.0,2500.0,North,Store,Bob
21,1021,2026-01-04,Headphones,1.0,500.0,West,Online,Bob
22,1022,2026-01-11,Headphones,4.0,500.0,South,Online,David
23,1023,2026-01-24,Headphones,5.0,2500.0,East,Online,Bob
24,1024,2026-01-07,Monitor,3.0,500.0,Unknown,In Store,Alice
25,1025,2026-01-08,Mouse,1.0,1000.0,Unknown,In Store,Unknown
26,1026,2026-01-09,Monitor,1.0,2500.0,North,In Store,Charlie
27,1027,NaT,Phone,3.0,500.0,Unknown,Online,Alice
28,1028,2026-01-05,Monitor,1.0,1000.0,Unknown,Online,Unknown
29,1029,2026-01-03,Keyboard,1.0,500.0,West,Online,Unknown
30,1030,2026-01-07,Tablet,3.0,1000.0,Unknown,Store,Charlie
31,1031,2026-01-05,Laptop,1.0,500.0,North,In Store,David
32,1032,NaT,Monitor,1.0,1000.0,Unknown,Unknown,Bob
33,1033,NaT,Phone,5.0,500.0,East,Online,Charlie
34,1034,NaT,Monitor,2.0,1000.0,South,Online,Bob
35,1035,2026-01-08,Mouse,5.0,1000.0,West,Store,Alice
36,1036,NaT,Phone,3.0,1500.0,East,Online,Bob
37,1037,NaT,Tablet,5.0,1500.0,Unknown,Online,Alice
38,1038,2026-01-03,Tablet,3.0,500.0,North,Store,Unknown
39,1039,2026-01-04,Headphones,1.0,2000.0,Unknown,In Store,Charlie

In [25]:
dg = dd.loc[dd["orderdate"].notna()]
dg

,orderid,orderdate,product,quantity,unitprice,region,channel,customer
0,1000,2026-01-01,Laptop,2.0,500.0,West,Unknown,David
1,1001,2026-01-02,Laptop,3.5,500.0,Unknown,Store,Bob
3,1003,2026-01-04,Laptop,3.0,2500.0,South,Unknown,Alice
5,1005,2026-01-06,Mouse,3.0,2000.0,North,Online,Bob
6,1006,2026-01-07,Keyboard,1.0,1000.0,South,Store,Charlie
7,1007,2026-01-08,Keyboard,1.0,1000.0,South,Online,Alice
8,1008,2026-01-09,Monitor,1.0,2000.0,South,In Store,Charlie
9,1009,2026-01-10,Phone,1.0,2500.0,North,In Store,Bob
12,1012,2026-01-13,Headphones,1.0,1500.0,Unknown,Online,Charlie
13,1013,2026-01-02,Phone,5.0,2500.0,South,Online,Alice
14,1014,2026-01-15,Mouse,2.0,2500.0,South,Online,Unknown
15,1015,2026-01-04,Phone,2.0,1500.0,East,Unknown,Bob
16,1016,2026-01-17,Headphones,4.0,2500.0,West,Online,Alice
17,1017,2026-01-06,Monitor,1.0,500.0,North,Online,Unknown
18,1018,2026-01-07,Tablet,2.0,2500.0,South,Store,Bob
19,1019,2026-01-02,Laptop,4.0,2000.0,West,Online,David
20,1020,2026-01-21,Mouse,2.0,2500.0,North,Store,Bob
21,1021,2026-01-04,Headphones,1.0,500.0,West,Online,Bob
22,1022,2026-01-11,Headphones,4.0,500.0,South,Online,David
23,1023,2026-01-24,Headphones,5.0,2500.0,East,Online,Bob
24,1024,2026-01-07,Monitor,3.0,500.0,Unknown,In Store,Alice
25,1025,2026-01-08,Mouse,1.0,1000.0,Unknown,In Store,Unknown
26,1026,2026-01-09,Monitor,1.0,2500.0,North,In Store,Charlie
28,1028,2026-01-05,Monitor,1.0,1000.0,Unknown,Online,Unknown
29,1029,2026-01-03,Keyboard,1.0,500.0,West,Online,Unknown
30,1030,2026-01-07,Tablet,3.0,1000.0,Unknown,Store,Charlie
31,1031,2026-01-05,Laptop,1.0,500.0,North,In Store,David
35,1035,2026-01-08,Mouse,5.0,1000.0,West,Store,Alice
38,1038,2026-01-03,Tablet,3.0,500.0,North,Store,Unknown
39,1039,2026-01-04,Headphones,1.0,2000.0,Unknown,In Store,Charlie